# Generated by Django 4.0.1 on 2022-01-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_max',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_min',
        ),
    ]
